replicaCount: 2
namespace: default
fullname: poc-app
image:
  repository: registry.gitlab.com/christiantragesser/docker-poc_app
  tag: latest
  pullPolicy: Always
service:
  name: poc-app
  type: ClusterIP
  externalPort: 5000
  internalPort: 5000
ingress:
  enabled: true
  hosts:
    - poc.ctt.io
  annotations:
    kubernetes.io/ingress.class: traefik
resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 5000
    scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 5000
    scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1