image: registry.gitlab.com/christiantragesser/dind-py:3

variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    LOCAL_TAG: local/poc_app
    EXT_TAG: $CI_REGISTRY/christiantragesser/docker-poc_app
    
services:
- name: docker:stable-dind
  command: ["--registry-mirror=https://dockerhub-mirror0.artifactory.asynchrony.com"]

stages:
  - test

test:
  stage: test
  script:
    - echo "$CI_COMMIT_SHA" > $CI_PROJECT_DIR/GIT_SHA
    - $CI_PROJECT_DIR/ci.py test
    - $CI_PROJECT_DIR/ci.py scan
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker tag $LOCAL_TAG ${EXT_TAG}:latest 
    - docker push ${EXT_TAG}:latest | grep -e "The push refers to" -e latest
  only:
    - master
  artifacts:
    paths:
    - "*.cve-scan.json"
    expire_in: 1 week
