image: christiantragesser/dind-ci

variables:
    DOCKER_DRIVER: overlay2
    
services:
- docker:stable-dind

stages:
  - test

test:
  stage: test
  script:
    - $CI_PROJECT_DIR/poc_ci.sh test
    - $CI_PROJECT_DIR/poc_ci.sh scan
  only:
    - master
  artifacts:
    paths:
    - "*.cve-scan.json"
    expire_in: 1 week
