replicaCount: 2
namespace: default
fullname: poc-app
image:
  repository: christiantragesser/poc_app
  tag: latest
  pullPolicy: Always
service:
  name: poc-app
  type: ClusterIP
  externalPort: 80
  internalPort: 80
ingress:
  enabled: true
  hosts:
    - example.com
  annotations:
    kubernetes.io/ingress.class: traefik
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 80
    scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 80
    scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
